# -*- coding: utf-8 -*-
"""azure_speech_text_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXm78s2iyHgtwnIcOofTQai_MyPWCTP6

# 🎙️ Speech to Text + 💬 Sentiment Analysis com Azure Cognitive Services
Este notebook realiza:
- Conversão de fala em texto (Azure Speech)
- Análise de sentimento no texto gerado (Azure Text Analytics)
"""

!pip install azure-cognitiveservices-speech requests

#  Configurações do Azure
# Substitua pelas suas chaves e endpoints

speech_key = "28j3eGE56aIqzFxUHMdZ7NEXodGlpnCNWrlqv03rW5f1CR2GGnMJQQJ99BDACYeBjFXJ3w3AAAaACOGJyCu"


speech_region = "eastus"

language_key = "03klPPjSMVEgWzfXkfAV4pM7Zt9hus2WGmKqCUAEF96HTJWTiqtiJQQJ99BDACYeBjFXJ3w3AAAaACOGqa5J"
language_endpoint = "https://language-marcos.cognitiveservices.azure.com/"

import azure.cognitiveservices.speech as speechsdk

def transcreve_audio(audio_path):
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=speech_region)
    audio_config = speechsdk.AudioConfig(filename=audio_path)
    recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    result = recognizer.recognize_once()
    print(" Texto reconhecido:", result.text)
    return result.text

# Exemplo de uso
audio_path = "audio.wav"  # coloque seu arquivo de áudio aqui (formato .wav)
texto = transcreve_audio(audio_path)
texto = "hoje o clima está muito bom"

import requests

def analisa_sentimento(texto):
    url = language_endpoint + "/text/analytics/v3.1/sentiment"
    headers = {
        "Ocp-Apim-Subscription-Key": language_key,
        "Content-Type": "application/json"
    }
    body = {
        "documents": [
            {"id": "1", "language": "pt", "text": texto}
        ]
    }

    response = requests.post(url, headers=headers, json=body)
    resultado = response.json()
    print("🔷 Resultado da API:", resultado)

    sentimento = resultado["documents"][0]["sentiment"]
    return sentimento

# 🟩 Parte fora da função!
sentimento = analisa_sentimento(texto)
print("✨ Sentimento detectado:", sentimento)